// Sujets repris du document précédent : ils ont été validés au fil des
// générations et n'ont pas à changer. Seul le CADRE autour d'eux est refait.
//
// Ajout par rapport à l'ancienne version : la MAIN qui tient l'arme est
// désormais nommée. C'est ce qui manquait pour que l'équipement reste du même
// côté d'une case à l'autre (ADR-070).
module.exports.WALKERS = [
  ["diablotin.png", "Diablotin de faille", 38, "petit diablotin violacé maigrichon, cornes courtes recourbées, grandes oreilles pointues, yeux jaunes luisants sans pupille, veines de lumière magenta courant sous la peau. Créature la plus faible du bestiaire : chétive, échine légèrement voûtée, mais en marche décidée. Mains nues, aucune arme."],
  ["goblin.png", "Gobelin", 46, "gobelin à la peau vert-de-gris, air hargneux, silhouette trapue. Armure de bric-à-brac faite de plaques dépareillées, casque de fer cabossé trop grand pour lui enfoncé jusqu'aux oreilles. Courte épée rouillée tenue basse dans la main DROITE, petit bouclier rond de planches clouées au bras GAUCHE."],
  ["orc.png", "Orc", 54, "orc guerrier massif à la peau vert olive, mâchoire lourde aux défenses inférieures proéminentes, petits yeux enfoncés. Épaules très larges, cou épais. Plastron de cuir clouté sur torse nu, brassards de fer. Hache de guerre large à une main, tenue basse dans la main DROITE."],
  ["troll.png", "Troll", 56, "troll gris-bleu voûté, peau rugueuse et verruqueuse, long nez crochu, oreilles tombantes, quelques touffes de cheveux filasse. Bras démesurés descendant presque au sol. Gourdin de bois brut traîné de la main DROITE. Dos courbé, épaules remontées."],
  ["dark_knight.png", "Chevalier noir", 58, "chevalier en armure de plates noire mate, heaume clos dont la visière étroite laisse filtrer une lueur rouge, aucune peau visible. Cape sombre déchirée en bas. Épée longue tenue pointe vers le bas le long de la jambe, dans la main DROITE. Élégant, martial et menaçant, surtout pas monstrueux ni difforme."],
  ["brute.png", "Brute", 62, "mort-vivant colossal et boursouflé, chair grisâtre verdâtre marquée de grosses sutures, mâchoire pendante, yeux laiteux. Le bras DROIT est nettement hypertrophié et pendant, le bras GAUCHE atrophié. Chaînes brisées aux poignets, lambeaux de tissu sale à la taille. Démarche lourde et déséquilibrée."],
  ["ogre.png", "Ogre", 66, "ogre énorme et bedonnant à la peau brun-rose, ventre proéminent, une seule grosse dent supérieure dépassant de la lèvre, petits yeux stupides. Corps très large, tête petite par rapport au tronc, exception à la règle de grosse tête. Pagne de peaux de bêtes, massue cloutée posée sur l'épaule DROITE."],
  ["golem.png", "Golem de fer", 70, "golem construit de lourdes plaques de fer rivetées, articulations mécaniques apparentes aux épaules et aux genoux, rouille sur les arêtes. Tête cubique sans visage, traversée d'une unique fente lumineuse bleu froid. Poings surdimensionnés, aucune arme. Démarche pesante et rigide."],
  ["warlord.png", "Chef de guerre", 72, "seigneur de guerre orc, chef de bande. Armure lourde sombre ornée de crânes et de trophées, épaulières hérissées de pointes, casque à grandes cornes recourbées, cape de fourrure épaisse sur les épaules. Énorme épée à deux mains portée sur l'épaule DROITE. Silhouette de boss : la plus imposante et la plus large des créatures humanoïdes."],
  ["frontier_raider.png", "Pillard des Frontières", 50, "bandit humain encapuchonné, silhouette agile et sèche. Capuche brune rabattue, écharpe sombre masquant le bas du visage, seuls les yeux visibles. Cuir clouté brun et sangles croisées sur le torse, ceinture garnie de petites fioles. Une dague courbe dans chaque main, tenues basses."],
  ["rift_marauder.png", "Maraudeur des Failles", 50, "guerrier humain corrompu par une magie de faille. Armure de plates grise fendue de longues fissures d'où s'échappe une lumière VIOLETTE intense. Le bras GAUCHE est entièrement cristallisé en éclats violets translucides remplaçant la chair. Heaume ouvert révélant un regard vide luminescent. Épée courte dans la main DROITE."],
  ["shade_warder.png", "Gardien des Ombres", 52, "sentinelle d'ombre élancée. Corps fait de fumée noire dense, maintenu en forme humanoïde par des sangles et des pièces d'armure argentées flottant à leur place : épaulières, brassards, ceinturon. Visage sans traits, deux fentes lumineuses blanches. Fine lame courbe argentée dans la main DROITE. Volutes sombres s'échappant des épaules. Les deux jambes restent nettement dessinées et distinctes."],
  ["veiled_assassin.png", "Assassin Voilé", 54, "assassin drapé de voiles gris-bleu en mouvement, écharpes flottant derrière lui. Visage entièrement masqué de bandelettes, aucun trait visible. Tenue ajustée sombre sous les voiles. Un poignard tenu en prise inversée dans chaque main, lames le long des avant-bras. Allure furtive mais avançant franchement. Les voiles ne doivent jamais masquer les jambes."],
  ["four_eyed_warden.png", "Gardien à Quatre Yeux", 58, "aberration humanoïde trapue à la peau bleu-gris coriace et plissée. QUATRE yeux jaunes disposés en losange sur un visage sans nez, bouche large et fine. Épaulières de pierre brute sanglées, pagne de cuir. Bâton-totem de bois noueux surmonté d'un fétiche osseux, tenu verticalement dans la main DROITE. Cou inexistant, épaules massives."],
  ["corrupted_hermit.png", "Ermite Corrompu", 64, "vieil ermite en haillons de toile grise, longue barbe emmêlée, dos courbé, appuyé sur un bâton de bois noueux tenu dans la main DROITE. La moitié GAUCHE de son corps est envahie par la corruption : cristaux violets translucides poussant hors de l'épaule et du bras, racines noires courant sur la peau, œil de ce côté remplacé par une lueur violette. L'autre moitié reste humaine et misérable. Contraste net entre les deux moitiés."],
  ["howling_bones.png", "Ossements Hurlants", 68, "amas de plusieurs squelettes fusionnés en une seule créature humanoïde. Deux cages thoraciques imbriquées formant le tronc, os surnuméraires saillant des épaules, bras composés de plusieurs avant-bras. Plusieurs crânes : un crâne principal bouche grande ouverte en plein hurlement, deux crânes secondaires soudés aux épaules. Flamme verte pâle dans chaque orbite. Os jaunis et fêlés. Les deux jambes restent complètes et séparées."],
  ["the_gravedigger.png", "Le Roi Fangeux, BOSS", 82, "BOSS FINAL du jeu. Roi mort-vivant colossal, silhouette écrasante et beaucoup plus large que tous les autres monstres. Couronne de fer tordue et rouillée enfoncée sur un crâne boursouflé, deux yeux verts luisants et haineux. Corps de boue et de chair putréfiée mêlée de racines noires, manteau de fange dégoulinante sur les épaules. Immense pelle-hache de fossoyeur tenue dans la main DROITE. Doit dominer par la présence : le monstre le plus imposant du bestiaire."],
];

module.exports.HERO = ["hero.png", "Héros du joueur", null, "chevalier héroïque, armure de plates d'acier CLAIR et lumineux à liserés dorés : la clarté de l'armure doit le distinguer instantanément des monstres sombres qui l'entourent. Heaume à visière ouverte laissant voir un regard déterminé, plumet ou crête sur le casque. Grand bouclier armorié au bras GAUCHE, blason au griffon. Épée longue à garde dorée dans la main DROITE, pointe vers le bas. Cape bleue."];

module.exports.STATICS = [
  ["wraith.png", "Spectre", 50, "portrait", "spectre encapuchonné, longue robe déchirée bleu-gris. Capuche vide d'où ne sortent que deux points de lumière froide en guise d'yeux. Mains squelettiques translucides. Le bas du corps ne se termine pas : il s'effiloche progressivement en volutes de brume bleu pâle qui se dissipent. Aspect semi-translucide, matière fantomatique."],
  ["bog_sprite.png", "Gelée Enragée", 36, "portrait", "blob de gelée vert marécage translucide et luisant, surface bombée réfléchissant la lumière. Débris pris en suspension à l'intérieur : petits os, brindilles, bulles d'air. Deux yeux jaunes furieux flottant dans la masse, bouche fendue en rictus. Coulures visqueuses sur le pourtour."],
  ["scorpion.png", "Scorpion des sables", 36, "plongee", "scorpion géant de désert, carapace segmentée sable et ocre, chitine mate et craquelée. Huit pattes fines bien écartées et distinctes. Deux pinces ouvertes tendues vers l'avant-gauche. Queue segmentée enroulée en arc au-dessus du dos et rabattue vers la droite, dard sombre nettement détaché sur le vide."],
  ["scarlet_prickler.png", "Piqueur Écarlate", 36, "plongee", "petite créature-oursin écarlate, corps rond bombé hérissé de longs piquants dressés rayonnant vers l'extérieur, pointes plus sombres. Six pattes fines et articulées dépassant sous le corps. Un œil unique jaune cerclé de noir au sommet, regard agressif. Vif et hargneux."],
  ["bat.png", "Chauve-souris", 52, "vol", "chauve-souris démoniaque, corps trapu et velu brun sombre, tête surdimensionnée aux grandes oreilles pointues, gueule ouverte montrant des crocs, petits yeux rouges luisants. Ailes membraneuses brun-pourpre largement nervurées, griffes aux articulations."],
  ["gargoyle.png", "Gargouille", 60, "vol", "gargouille de pierre grise animée, texture minérale rugueuse. Tête de démon aux cornes recourbées, gueule ouverte, yeux ambrés. Ailes de PIERRE déployées, épaisses et anguleuses, pas membraneuses. Fissures parcourant le corps et les ailes, laissant filtrer une lueur ambrée depuis l'intérieur. Griffes de pierre."],
  ["wyvern.png", "Vouivre", 78, "vol", "vouivre, dragon BIPÈDE à deux pattes seulement, écailles vert-bronze. Cou tendu vers l'avant, gueule ouverte montrant des crocs, cornes en arrière du crâne, yeux jaunes. Deux grandes ailes membraneuses. Longue queue s'achevant en dard, enroulée sous le corps et bien détachée. Le plus imposant des volants."],
];

module.exports.TOWERS = [
  ["tower_archer.png", "Archerie, paliers 1-2", "tourelle d'archerie médiévale modeste, deux niveaux. Soubassement de pierre grise appareillée, étage supérieur en poutres et planches de bois brun. Plateforme de tir ouverte couverte d'un petit toit de bardeaux à deux pentes. Meurtrières étroites, échelle de bois appuyée, carquois de flèches posés sur la plateforme."],
  ["tower_archer_t3.png", "Archerie, palier 3", "tourelle d'archerie médiévale AMÉLIORÉE, version évoluée de la même tour : mêmes matériaux (pierre grise en bas, bois brun en haut), même angle, mais TROIS niveaux au lieu de deux. Créneaux de pierre, poutres sculptées et ferrures, toit de bardeaux renforcé, bannière flottant au sommet, réserves de flèches. Nettement plus haute et plus riche que la version de base, tout en restant reconnaissable comme la même tour."],
  ["tower_archer_spec_longbow.png", "Spécialisation « Arc long »", "tour d'archerie de pierre et de bois surmontée d'une GRANDE ARBALÈTE DE SIÈGE À CARREAU UNIQUE montée sur pivot. Arc d'acier tendu par de gros câbles, treuil d'armement, un unique carreau massif à pointe de fer chargé et pointé. Silhouette élancée et perçante, notion de tir unique et puissant."],
  ["tower_archer_spec_volley.png", "Spécialisation « Volée »", "tour d'archerie de pierre et de bois surmontée d'un RÂTELIER DE PLUSIEURS ARCS MÉCANIQUES disposés EN ÉVENTAIL, chacun chargé, l'ensemble prêt à lâcher une gerbe de flèches simultanée. Sommet nettement plus LARGE que la tour de base, notion de tir groupé et de saturation."],
  ["tower_frost.png", "Givre, paliers 1-2", "tour de pierre bleutée trapue, deux niveaux, sommet ouvert. Un CRISTAL DE GLACE translucide cyan flotte au-dessus de la plateforme, légèrement en lévitation. Givre blanc rampant sur les pierres et les arêtes, petites stalactites sous les corniches, brume froide bleutée à la base de la tour."],
  ["tower_frost_t3.png", "Givre, palier 3", "tour de givre AMÉLIORÉE, version évoluée de la même tour : même pierre bleutée, même angle, mais trois niveaux et un cristal de glace BEAUCOUP PLUS GRAND, entouré de plusieurs éclats de glace en orbite. Arcs de glace reliant les niveaux, longues stalactites, lueur cyan nettement plus intense. Reconnaissable comme la même tour, en plus puissante."],
  ["tower_frost_spec_frostfire.png", "Spécialisation « Givre ardent »", "tour de givre en pierre bleutée dont le cristal sommital est TRAVERSÉ D'UNE FLAMME ORANGE VIF. Autour du cristal, un tourbillon mêlant éclats de glace cyan et langues de feu orange, les deux entrelacés. Contraste chaud/froid marqué et immédiatement lisible : moitié bleu glacé, moitié orange ardent."],
  ["tower_frost_spec_blizzard.png", "Spécialisation « Blizzard »", "tour de givre en pierre bleutée surmontée d'un TOURBILLON DE NEIGE EN SPIRALE, vortex blanc et cyan tournoyant au-dessus de la plateforme, éclats de glace emportés dans la rotation, traînées de vent circulaires. Dominante blanc-cyan, effet de tempête localisée."],
];

module.exports.UI = [
  ["castle-blue.png", "Le Bastion, emblème de la tuile Histoire", "320×256, paysage", "château fort médiéval compact et trapu, symbole d'un bastion assiégé. Donjon carré central en pierre claire, deux tourelles latérales coiffées de toits coniques BLEU ardoise, courtine crénelée les reliant. Grande porte cloutée fermée d'une herse de fer. Bannières bleues flottant aux sommets. Aspect solide et rassurant, pas menaçant."],
  ["icons/bestiary-book.png", "Grimoire du Bestiaire", "192×286, portrait", "gros grimoire ancien FERMÉ. Couverture de cuir sombre usé, ferrures et cornières de laiton aux angles, fermoir métallique sur la tranche, gros médaillon gravé au centre de la couverture. Tranche des pages jaunie et dorée sur le bord, un marque-page de ruban rouge dépassant du bas. Aspect de vieux livre de savoir, précieux et lourd."],
  ["tiny-swords/ui/icon-06.png", "Emblème Armurerie", "64×64", "bouclier héraldique métallique traversé en diagonale par une épée, garde dorée. Bordure de métal clair, cœur du bouclier bleu, rivets visibles."],
  ["tiny-swords/ui/icon-05.png", "Emblème Chroniques", "64×64", "deux épées croisées en X, lames d'acier clair pointées vers le haut, gardes et pommeaux dorés, poignées de cuir brun."],
  ["tiny-swords/ui/icon-12.png", "Emblème Son", "64×64", "lyre dorée médiévale de face, cadre doré et cordes claires, ou à défaut une grosse note de musique dorée à hampe épaisse."],
];
